### ISSUE TITLE
SyntaxError in `dump_model` from `utils.py`

### ISSUE THREAD

**Issue by GiuliaGualtieri** [OpenMined/syft-heart-disease-tutorial#1]
## Description
I got a **SyntaxError** while executing the tutorial `02-Model-Training-Experiment.ipynb`
```python
from utils import dump_model

  File ~/syft-heart-disease-tutorial/utils.py:31
    return f"{datasite_name.replace(".", "").replace(" ", "_").lower()}_model.jbl"
                                     ^
SyntaxError: f-string: unmatched '('
```

## How to Reproduce
1. Go to `02-Model-Training-Experiment.ipynb`
2. Run the code.
3. Scroll down to 'Step 4. Train Models on all datasites'
4. Then you should get a SyntaxError

## Expected Behavior
No errors. My suggested solution: replace
```python
def get_model_file(datasite_name: str) -> str:
    return f"{datasite_name.replace(".", "").replace(" ", "_").lower()}_model.jbl"
```
with the following code
```python
def get_model_file(datasite_name: str) -> str:
    return f"{datasite_name.replace('.', '').replace(' ', '_').lower()}_model.jbl"
```

## System Information
 - macOS: 14.5
 - Language Version: Python 3.11.10
 - Package Manager Version: Conda 24.3.0

**Comment by bvermeul** [comment]
just ran into the same with the same solution. It's also in the 01-Compare-Demographics notebook.

**Comment by leriomaggio** [comment]
Thank you very much both of you for reporting the blunder (and the fix!)

It must have been an error induced by the `black` formatter. 
Hot fix added and merged to the repo! 

Many thanks!
